name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Add EC2 to known hosts
        run: |
          ssh-keyscan -H 13.61.182.189 >> ~/.ssh/known_hosts

      - name: Deploy to EC2
        run: |
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa ec2-user@13.61.182.189 << 'EOF'
            sudo docker rm -f backend || true
            sudo docker rmi karoshalex0873/skillmatch_ai || true
            sudo docker pull karoshalex0873/skillmatch_ai
            sudo docker run -d -p 80:80 --name backend karoshalex0873/skillmatch_ai
          EOF
